### PR TITLE
create Docker containers and remove envmodules

### LINKED ISSUE #42: Containerize major rules
BIOWULF keeps discontinuing certain tools without prior notice. Hence containerize tools to avoid breaking rules of the pipeline.
 - [ ] CircExplorer
 - [ ] CIRI
 - [ ] CLEAR
 - [ ] NCLscan
 - [ ] MapSplice
 - [ ] DCC

### LINKED ISSUE #99: convert to platform-agnostic pipeline
- switch modules to containers (#42)
- remove any biowulf-specific code from driver script
- remove hard-coded biowulf paths from config, or document them well
- test on FRCE to verify that it works off biowulf

development in progress here: `/data/CCBR_Pipeliner/Pipelines/CHARLIE/charlie-dev-sovacool`

### LINKED ISSUE #101: python 3.7 module is deprecated
this error is encountered when executing a `dryrun` or `run` on biowulf

```sh
/data/Ziegelbauer_lab/Pipelines/circRNA/v0.10.1/charlie \
    -w=/data/Ziegelbauer_lab/circRNADetection/sovacoolkl_charlie/charlie_v0.10.1 \
    -m=dryrun
```

### LINKED ISSUE #106: add option for different tmp-dir
eg from renee `--tmp-dir /scratch/cluster_scratch/$USER`

### LINKED ISSUE #108: set singularity cachedir to workdir
just like RENEE

create a flag for users to override this behavior if desired

### PR DESCRIPTION
**Pull request by kelly-sovacool**
## Changes

- Set container URLs in config file
- Specify containers for all rules instead of envmodules
- Create containers as needed in `docker/`, with github actions to update them

## Issues

- resolves #42 
- resolves #99 
- resolves #101 
- resolves #106  
- resolves #108 

## Checklist

- [x] update changelog

### CODE REVIEW

**Comment by kelly-sovacool** [comment]
also need to copy resources from zeigelbauer dir to shared pipeliner dir

**Comment by kelly-sovacool** [comment]
test runs completed succesfully on biowulf and FRCE. @kopardev this is ready for your review.

**Review by kopardev — APPROVED** [review]
deserves minor release increment.

**Comment by kelly-sovacool** [comment]
> deserves minor release increment.

previously (#107 & #110) we had planned on the next version being v1.0.0 after this PR -- do you think it should be v0.11.0 instead?

**Pull request merged**
